// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Creuna.FluidImages")]
[assembly: AssemblyProductAttribute("Creuna.FluidImages")]
[assembly: AssemblyDescriptionAttribute("An EPiServer plugin enabling editors to set the focus point of an image")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
        internal const string InformationalVersion = "1.0";
    }
}
