// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Creuna.FluidImages")]
[assembly: AssemblyProductAttribute("Creuna.FluidImages")]
[assembly: AssemblyDescriptionAttribute("An EPiServer plugin enabling editors to set the focus point of an image")]
[assembly: AssemblyVersionAttribute("0.0.3")]
[assembly: AssemblyFileVersionAttribute("0.0.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Creuna.FluidImages";
        internal const System.String AssemblyProduct = "Creuna.FluidImages";
        internal const System.String AssemblyDescription = "An EPiServer plugin enabling editors to set the focus point of an image";
        internal const System.String AssemblyVersion = "0.0.3";
        internal const System.String AssemblyFileVersion = "0.0.3";
    }
}
