// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Creuna.FluidImages.TestSite")]
[assembly: AssemblyProductAttribute("Creuna.FluidImages")]
[assembly: AssemblyDescriptionAttribute("An EPiServer plugin enabling editors to set the focus point of an image")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
        internal const string InformationalVersion = "0.0.1";
    }
}
